from pydantic import BaseModel, Field
from typing import Optional, List, Dict

# Feature 1: Fan Navigator Models
class NavigatorRequest(BaseModel):
    query: str = Field(..., description="Fan query about directions, seating, gates, etc.")
    language: Optional[str] = Field(None, description="Optional target language (English, Hindi, Spanish, Arabic). Auto-detected if null.")

class NavigatorResponse(BaseModel):
    answer: str = Field(..., description="Grounded navigation directions in the query language.")
    detected_language: str = Field(..., description="The language detected (or specified).")

# Feature 2: Crowd Intelligence Models
class ZoneStatus(BaseModel):
    zone_name: str = Field(..., description="Name of the zone (e.g., Zone A).")
    capacity_pct: float = Field(..., description="Current density/capacity percentage (0.0 to 100.0).")
    trend: str = Field(..., description="Capacity trend: UP, DOWN, or STABLE.")

class CrowdStatusResponse(BaseModel):
    zones: List[ZoneStatus]
    match_phase: str = Field(..., description="Simulated current match phase.")
    simulated_time: str = Field(..., description="Human-readable match time desc.")
    timestamp: float = Field(..., description="Epoch timestamp of current status.")

class CrowdAlertRequest(BaseModel):
    zones: List[ZoneStatus] = Field(..., description="Current status of all zones.")
    match_phase: Optional[str] = Field(None, description="Current match phase.")
    simulated_time: Optional[str] = Field(None, description="Current match time desc.")

class CrowdAlertResponse(BaseModel):
    alerts: List[str] = Field(..., description="List of 1 to 3 short operational alerts generated by Gemini.")
    flow_suggestion: str = Field(..., description="One-line entry/exit flow recommendation.")

# Feature 3: Volunteer / Staff Assistant Models
class VolunteerQueryRequest(BaseModel):
    query: str = Field(..., description="Staff/volunteer question about emergency or operational protocol.")

class VolunteerQueryResponse(BaseModel):
    answer: str = Field(..., description="Answer to the query, strictly grounded in the volunteer KB.")
    grounded_on: List[str] = Field(..., description="List of titles of KB entries that were matched and used.")

# Feature 4: Sustainability Tracker Models
class TransportSplit(BaseModel):
    car: float = Field(..., description="Percentage of fans traveling by car (0 to 100).")
    bus: float = Field(..., description="Percentage of fans traveling by bus (0 to 100).")
    metro: float = Field(..., description="Percentage of fans traveling by metro (0 to 100).")
    walk: float = Field(..., description="Percentage of fans walking or cycling (0 to 100).")

class SustainabilityRequest(BaseModel):
    fan_count: int = Field(..., description="Total number of fans attending.")
    transport_split: TransportSplit = Field(..., description="Transportation mode split percentages (should sum to approximately 100).")
    avg_distance_km: float = Field(..., description="Average travel distance per fan in kilometers.")

class SustainabilityResponse(BaseModel):
    total_kg_co2: float = Field(..., description="Total calculated carbon emissions in kilograms of CO2.")
    per_fan_kg_co2: float = Field(..., description="Average carbon emission per fan in kilograms of CO2.")
    suggestions: List[str] = Field(..., description="Actionable GenAI reduction suggestions based on the transport split.")
